version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout

      - restore_cache:
          keys:
          - cache-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            #sed -i 's/tensorflow==/tensorflow-cpu==/' requirements.txt
            pip install -r requirements.txt

      - save_cache:
          key: cache-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: run linting
          when: always
          command: |
            PYTHONPATH=. ./lint.sh

      - store_artifacts:
          path: test-reports
          destination: test-report


          